#!/usr/bin/python2
"""
   Copyright 2017 The Trustees of Princeton University

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""


import os
import sys
import traceback

import syndicate.util.gateway as gateway

if __name__ == "__main__":
  
    # it's okay if the driver doesn't have a 'serialize' or 'deserialize' method 
    default_callbacks = {
      'serialize': None,
      'deserialize': None,
      'cdn_url': None
    }

    usage, driver_mod = gateway.driver_setup( ['cdn_url', 'serialize', 'deserialize'], \
                                             ['cdn_url', 'serialize', 'deserialize'],
                                             default_callbacks=default_callbacks )

    # ready to go!
    # tell the parent that we're ready 
    print "0"
    sys.stdout.flush()

    if usage == 'cdn_url':
        while True:

            # accept a URL on stdin
            # read size...
            size = gateway.read_int( sys.stdin )
            if size is None:
                sys.exit(3)

            # read URL...
            url = gateway.read_data(sys.stdin, size)
            if url is None:
                sys.exit(3)

            # feed into driver
            gateway.log_debug("Translate '{}' into a CDN-compatible URL".format(url))

            try:
                new_url = driver_mod.cdn_url(url, driver_mod.CONFIG, driver_mod.SECRETS)
            except Exception, e:
                gateway.log_error("cdn_url failed")
                gateway.log_error(traceback.format_exc())
                sys.exit(4)

            # send back the URL 
            gateway.log_debug("write back URL '{}'".format(new_url))
            gateway.write_chunk(sys.stdout, new_url)
            
            sys.stdout.flush()
            sys.stderr.flush()

